export const REGISTER_USER = 'usuario/cadastrar'
export const LOGIN = 'usuario/logar'
export const ALL_SERVICES = 'servicos/all'
export const USER_ATTENDANCE = 'agendamento/'
export const UPDATE_USER = 'usuario/atualizar'
export const ALL_ATTENDANCES = 'agendamento/all'
